name: CommandSpy
main: pw.kaboom.commandspy.Main
description: Plugin that allows you to spy on players' commands.
api-version: 1.13
version: master
folia-supported: true

commands:
   commandspy:
      aliases: [c,cs,cspy]
      description: Allows you to spy on players' commands
      usage: /commandspy
      permission: commandspy.command
